apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/name: tekton-results-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tekton-results-api
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app.kubernetes.io/name: tekton-results-api
    spec:
      serviceAccountName: api
      containers:
        - name: api
          image: api-server:latest
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: tekton-results
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tekton-results
                  key: POSTGRES_PASSWORD
            - name: DB_PROTOCOL
              value: tcp
            - name: DB_ADDR
              value: tekton-results-postgres-service.tekton-pipelines.svc.cluster.local
            - name: DB_NAME
              value: tekton-results
          volumeMounts:
            - name: tls
              mountPath: "/etc/tls"
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: tekton-results-tls
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: tekton-pipelines
spec:
  selector:
    app.kubernetes.io/name: tekton-results-api
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: prometheus
      protocol: TCP
      port: 8080
      targetPort: 8080
